version: 2.1

jobs:
  build: 
      docker:
        - image: cimg/python:3.8
      steps:
        - checkout
        - run: 
           name: Run main.py
           command: python main.py
  test:
      docker:
      - image: cimg/python:3.8
      steps:
       - checkout
       - run: 
           name: run main.py
           command: python -m unittest test.py
workflows:
   build_and_test:
      jobs:
         - build
         - test 